services:
  db:
    image: postgres
    container_name: db_estudos_musicais
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-mem
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: